spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/TicTacToe"
    username: postgres
    password: Ivandr_2004
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081
  error:
    include-message: always