

spring:
  datasource:
    url: "jdbc:postgresql://tic-tac-toe-db.c6jamauu7csz.eu-central-1.rds.amazonaws.com:5432/TicTacToe"
    username: postgres
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081
  error:
    include-message: always